# This travis file will add continuous integration to the project 
language: generic
sudo: required 
service: 
  - docker

before_install:
  - docker build -t hordyhordan/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true hordyhordan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_env: "elasticbeanstalk-us-west-1-377279116230"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"