language: generic
sudo: required 
service: 
  - docker

before_install:
  - docker build -t hordyhordan/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true hordyhordan/docker-react npm run test -- --coverage