version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app 
    command: ["npm", "run", "test"]